name: Checks
on:
  - push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: package.json
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install modules
        run: corepack yarn
      - name: Run lint check
        run: corepack yarn run lint
      - name: Run format check
        run: corepack yarn run check:format
      - name: Run type check
        run: corepack yarn run check:types
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: package.json
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install modules
        run: corepack yarn
      - name: Run tests
        run: corepack yarn run test
